from __future__ import annotations

import json

from langchain.tools import ToolRuntime, tool
from langchain_core.messages import HumanMessage, ToolMessage

from ..agents.intent.graph import intent_agent
from ..agents.market.graph import market_agent
from ..agents.route.graph import route_agent
from ..agents.relation.graph import relation_agent
from ..agents.personalization.graph import personalization_agent
from ..domain.market_mapping import dataset_category_for_node
from ..domain.market_cache import MarketCache


@tool
def call_intent_agent(request: str) -> str:
    """Interpret a shopping request, including any relevant conversation context."""
    return intent_agent.invoke(request).model_dump_json()


@tool
def call_route_agent(product: str) -> str:
    """Resolve one normalized product name to the canonical product taxonomy."""
    return route_agent.invoke(product).model_dump_json()


@tool
def call_market_agent(node_id: str) -> str:
    """Reuse saved criteria and attributes for a resolved node, researching only on a cache miss."""
    cache = MarketCache()
    node = cache.node(node_id)
    cached = cache.load(node)
    if cached is not None:
        return cached.model_dump_json()
    query = dataset_category_for_node(node_id)
    result = market_agent.invoke(query, target=node.node_path)
    if result.status == "completed":
        cache.save(node, result)
    return result.model_dump_json()


@tool
def call_relation_agent(node_id: str) -> str:
    """Reuse or research a relation graph after this node's completed Market Profile is saved."""
    return relation_agent.invoke(node_id).model_dump_json()


def _user_message_text(message: HumanMessage) -> str:
    """Normalize plain and block-based text without stringifying non-text payloads."""
    if isinstance(message.content, str):
        return message.content
    parts = []
    for block in message.content:
        if isinstance(block, str):
            parts.append(block)
        elif (isinstance(block, dict) and block.get("type") == "text"
              and isinstance(block.get("text"), str)):
            parts.append(block["text"])
        else:
            raise ValueError("personalization does not support non-text user content blocks")
    return "\n".join(parts)


def _personalization_history(runtime: ToolRuntime, task_id: str | None = None):
    thread_id = runtime.config.get("configurable", {}).get("thread_id")
    if not thread_id:
        raise ValueError("personalization requires a configured thread_id")
    users = [m for m in runtime.state["messages"] if isinstance(m, HumanMessage)]
    if not users or not users[-1].id:
        raise ValueError("personalization requires user messages with stable IDs")
    if task_id is None:
        task_id = users[-1].id
    else:
        # Completion cannot silently absorb a later shopping task's user messages.
        for message in reversed(runtime.state["messages"]):
            if isinstance(message, ToolMessage) and message.name == "prepare_personalization":
                try:
                    prepared = json.loads(message.content)
                except (TypeError, ValueError):
                    continue
                if isinstance(prepared, dict) and "task_id" in prepared:
                    if prepared["task_id"] != task_id:
                        raise ValueError("only the latest prepared shopping task can be updated")
                    break
    start = next((i for i, m in enumerate(users) if m.id == task_id), None)
    if start is None:
        raise ValueError("task start message is not present in this conversation")
    messages = [_user_message_text(m) for m in users[start:]]
    return str(thread_id), task_id, messages


@tool
def prepare_personalization(node_id: str, runtime: ToolRuntime) -> str:
    """Start personalization for the latest user request after its relation graph is ready."""
    thread_id, task_id, messages = _personalization_history(runtime)
    questions = personalization_agent.prepare_questions(node_id, messages,
        thread_id=thread_id, task_id=task_id)
    return json.dumps({"task_id": task_id, "node_id": node_id,
                       "question_set": questions.model_dump()}, ensure_ascii=False)


@tool
def complete_personalization(node_id: str, task_id: str, runtime: ToolRuntime) -> str:
    """Generate/save preferences after feedback, or update them from the full task history.

    Use the exact task_id returned by prepare_personalization. User text and thread identity
    are read from runtime, not generated by the supervisor.
    """
    thread_id, task_id, messages = _personalization_history(runtime, task_id)
    return personalization_agent.personalize(node_id, messages,
        thread_id=thread_id, task_id=task_id).model_dump_json()


SUPERVISOR_TOOLS = [
    call_intent_agent,
    call_route_agent,
    call_market_agent,
    call_relation_agent,
    prepare_personalization,
    complete_personalization,
]
